### ISSUE TITLE
Persistent Volume is not released after done building the pipelineruns

### ISSUE THREAD

**Issue by tam512** [kabanero-io/kabanero-pipelines#123] opened 2019-11-12 19:50 UTC
- Using OCP 4.2 with Kabanero Operator 0.3.0-rc.2 
- Create Persistent volume using pv.yaml file
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: appsody-manual-pipeline-run-pvc
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /var/lib/appsody-manual-pipeline-run-pvc
```
- Trigger a pipeline run using `java-microprofile-build-push-deploy-pipeline`, after it's done buildiing.  I see that the PV is still Bound and not released

```
$ oc get pv
NAME                               CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                                                   STORAGECLASS   REASON    AGE
appsody-manual-pipeline-run-pvc    5Gi        RWO            Recycle          Bound       kabanero/che-jmp-webhook-1573513014-gcn78-r-hjhfh-pvc                            35m
                           14m
$ oc get pvc
NAME                                           STATUS        VOLUME                             CAPACITY   ACCESS MODES   STORAGECLASS   AGE
che-jmp-webhook-1573513014-gcn78-r-hjhfh-pvc   Terminating   appsody-manual-pipeline-run-pvc    5Gi        RWO                           3h52m

$ oc describe pvc che-jmp-webhook-1573513014-gcn78-r-hjhfh-pvc
Name:          che-jmp-webhook-1573513014-gcn78-r-hjhfh-pvc
Namespace:     kabanero
StorageClass:  
Status:        Terminating (lasts 3h)
Volume:        appsody-manual-pipeline-run-pvc
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed=yes
               pv.kubernetes.io/bound-by-controller=yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      5Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Events:        <none>

```

**Comment by mtamboli** [comment] 2019-11-12 19:59
I am seeing the same issue where volumes are bound even though no pipeline run in active:
```
pvc-04c9da0b-04e4-11ea-9aee-00000a1006d8   5Gi        RWO            Delete           Bound    kabanero/wh-jee-1573518796-72rtg-pvc                 managed-nfs-storage            19h
pvc-156de9d3-04c8-11ea-9aee-00000a1006d8   5Gi        RWO            Delete           Bound    kabanero/mst-mp-webhook-1573506798-4wzppvc           managed-nfs-storage            22h
pvc-b8d439ff-04cc-11ea-9aee-00000a1006d8   5Gi        RWO            Delete           Bound    kabanero/mst-mp-webhook-1573506798-4wzpr-cbxqj-pvc   managed-nfs-storage            22h

```

**Comment by smcclem** [comment] 2019-11-13 22:47
Currently blocked by Fyre infrastructure issue. 

https://ibm-cloudplatform.slack.com/archives/C23SLUR42/p1573680579317400

Our team doesn't have any spare OCP 4.2 Fyre system to debug this issue on, and I can't setup a new system to use at the moment.  I will continue to try to get the Fyre env. setup, and follow the progress of the issue on the slack Fyre discussion channel.

**Comment by kvijai82** [comment] 2019-11-15 12:42
We reproduced this.  The PVC seems to be stuck in terminating state and we are investigating why that is the case.  Ruled out the container scan being a potential cause of the issue.  Also trying to setup a 3.1.1 cluster to check the behavior there.

**Comment by marikaj123** [comment] 2019-11-18 21:01
Needs time to diagnose the problem.  It is not a stopship, in debugging mode to find out where the issue may exist.

**Comment by marikaj123** [comment] 2019-12-03 19:33
Scott is working with the Tekton team. It needs more debugging.

**Comment by marikaj123** [comment] 2019-12-10 20:52
According to Scott, the team continues to debug and waiting for help from the public Tekton slack channel. @anneqm - Anne, would your team be able to help here?

**Comment by marikaj123** [comment] 2019-12-16 18:25
Vijai will conatct @smcclem to decide if the expected behaivior .

**Comment by kvijai82** [comment] 2019-12-16 19:01
@anneqm we think it's possible that the change of behavior to not release the PV after the pipelinerun is done could be desired behavior to preserve any data that's associated with the pipeline run.  We could like some confirmation from the Tekton team that this is the desired behavior and was changed intentionally.  We discussed this with Adam before and he tried to ask this question on the public Tekton channel but got no response.  I tried to repost his question and also got no response.

https://tektoncd.slack.com/archives/CLCCEBUMU/p1574091061131000

**Comment by anneqm** [comment] 2019-12-16 21:56
@mnuttall Mark, can you take a look?  thank you.

**Comment by anneqm** [comment] 2019-12-18 14:59
@kvijai82 would you please raise this as an issue on https://github.com/tektoncd/pipeline repo?

**Comment by mnuttall** [comment] 2019-12-18 15:01
Hi @tam512 @kvijai82 please open this in github.com/tektoncd/pipeline and we'll see what help we can give from there - thank you.

**Comment by kvijai82** [comment] 2019-12-23 12:00
Opened issue https://github.com/tektoncd/pipeline/issues/1784 for it.

**Comment by kvijai82** [comment] 2020-01-08 15:46
No updates in Tekton issue.  I have updated the pipeline troubleshooting doc documenting this behavior.

**Comment by marikaj123** [comment] 2020-01-08 16:48
Vijai, will be adding a link to the debugging section.  Marika will talk to @anneqm about opening a feature with Tekton.

**Comment by vtereso** [comment] 2020-01-16 14:51
PV/PVC have finalizers on them, which prevent them from being deleted while the mounting pods still exist. Since there is still no community approved way to persist/read logs outside of the pod, there is also no intent to delete the pods outside of deleting the corresponding/owner `PipelineRun`. From yesterday's community call, the consensus was that this is working as intended.

**Comment by anneqm** [comment] 2020-01-16 15:10
@marikaj123 @smcclem @kvijai82 Since this is working as intended, suggest updating the documentation with instruction on how to release the PV to close this issue for now?

**Comment by kvijai82** [comment] 2020-01-16 17:29
Added entry to pipelines troubleshooting guide here explaining this behavior:  https://github.com/kabanero-io/kabanero-pipelines/blob/master/Troubleshooting.md

Tekton team to discuss enhancing this behavior in the future in weekly call.  Closing this out as discussed earlier.

**Closed by kvijai82** 2020-01-16 17:29 UTC
Labels: bug

**Comment by anneqm** [comment] 2020-01-16 19:05
@kvijai82 also, here's the PR @vtereso opened in the tekton pipeline repo to address similar comment in Tekton documentation.  Thanks everyone!  https://github.com/tektoncd/pipeline/pull/1885
