### ISSUE TITLE
Kabanero pipelines updated to use the tekton pipeline beta version

### ISSUE THREAD

**Issue by anneqm** [kabanero-io/kabanero-pipelines#283] opened 2020-03-30 22:57 UTC
Tekton beta pre-release is available with v0.11.0-release candidate 4. This will be the last RC before the beta release is declared this week. Please see release notes for the changes, deprecation notices, and backward incompatibilities. 
https://github.com/tektoncd/pipeline/releases. 

Migration guide: https://github.com/tektoncd/pipeline/blob/master/docs/migrating-v1alpha1-to-v1beta1.md

**Comment by marikaj123** [comment] 2020-04-20 23:56
@tseelbach and @kvijai82 the release https://github.com/operator-framework/community-operators/tree/master/community-operators/openshift-pipelines-operator/0.11.0

**Comment by brianxjx** [comment] 2020-04-29 21:35
A PR has been published with changes verified with workarounds on Kabanero 0.9.0 alpha.2.

1. Found what looks like a bug in the Tekton dashboard regarding webhook creation.
2. A change was made to the Tekton namespace installation.  Waiting for a decision from Tekton dashboard and Kabanero operator.

**Comment by aadeshpa** [comment] 2020-04-30 17:36
The changes from pipelines side is merged in pipelines repo for 0.9.0. @brianxjx is waiting to test it once he gets the new alpha operator release cut from @kaczyns

**Comment by marikaj123** [comment] 2020-04-30 19:45
@aadeshpa  and @brianxjx - Is this the release that you are looking for: https://github.com/kabanero-io/kabanero-operator/releases/tag/0.9.0-alpha.3

**Comment by aadeshpa** [comment] 2020-05-01 19:23
@marikaj123 : The issue is ,0-9-0-alpha.4 is present in operator releases, however what Brian needs is updated pipelines release files present in operator release. However since kabanero-pipelines-0.9.0rc1 is not yet cut, the operator cannot create a new release with the updated pipelines. Hence Brian would need to wait to test this on Monday. 

None the less, we have verified the pipelines updates with his changes of this issue by manually applying the pipelines files in the cluster and driving it via webhook. So we are green with the changes merged for this issue.

**Comment by aadeshpa** [comment] 2020-05-01 22:36
Verified by installing kabanero-operator 0.9.0-alpha.4, and manually updated default.yaml to use pipelines 
url: https://github.com/kabanero-io/kabanero-pipelines/releases/download/0.9.0-rc.1/default-kabanero-pipelines.tar.gz
sha256: bad7d41f69b470d1c78ccc2720e8583e8a1a549dd4ec8e9056e1f2c89d825029

Used webhook to drive a pipeline for build-deploy-pl and it passed successfully. Marking this issue as closed.

**Comment by aadeshpa** [comment] 2020-05-01 22:36
<img width="1390" alt="Screen Shot 2020-05-01 at 6 36 14 PM" src="https://user-images.githubusercontent.com/53223993/80846581-b2f8c280-8bda-11ea-85cd-512f777d1e47.png">

**Closed by aadeshpa** 2020-05-01 22:36 UTC
Labels: status-Green
