### ISSUE TITLE
Serviceability: need better error message when missing github secret

### ISSUE THREAD

**Issue by tam512** [kabanero-io/kabanero-pipelines#54] opened 2019-09-09 19:58 UTC
when building nodejs express through tekton pipeline and the github secret is missing, the build is fail with error `could not read Username for 'https://github.ibm.com': No such device or address`.  Can we add a message to let users know that they need to create a secret for github?

Below is the full error:
```
{"level":"warn","ts":1568057939.538,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
{"level":"error","ts":1568057939.8545134,"logger":"fallback-logger","caller":"git/git.go:35","msg":"Error running git [fetch --depth=1 --recurse-submodules=yes origin fc7fe7fb8d87779dd5419b509dd2c91e63ba87b7]: exit status 128\nfatal: could not read Username for 'https://github.ibm.com': No such device or address\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\t/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:35\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\t/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:88\nmain.main\n\t/go/src/github.com/tektoncd/pipeline/cmd/git-init/main.go:36\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:198"}
{"level":"error","ts":1568057940.1771348,"logger":"fallback-logger","caller":"git/git.go:35","msg":"Error running git [pull --recurse-submodules=yes origin]: exit status 1\nfatal: could not read Username for 'https://github.ibm.com': No such device or address\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\t/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:35\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\t/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:91\nmain.main\n\t/go/src/github.com/tektoncd/pipeline/cmd/git-init/main.go:36\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:198"}
{"level":"warn","ts":1568057940.1772096,"logger":"fallback-logger","caller":"git/git.go:92","msg":"Failed to pull origin : exit status 1"}
{"level":"error","ts":1568057940.1798232,"logger":"fallback-logger","caller":"git/git.go:35","msg":"Error running git [checkout fc7fe7fb8d87779dd5419b509dd2c91e63ba87b7]: exit status 128\nfatal: reference is not a tree: fc7fe7fb8d87779dd5419b509dd2c91e63ba87b7\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\t/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:35\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\t/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:94\nmain.main\n\t/go/src/github.com/tektoncd/pipeline/cmd/git-init/main.go:36\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:198"}
{"level":"fatal","ts":1568057940.179904,"logger":"fallback-logger","caller":"git-init/main.go:37","msg":"Error fetching git repository: exit status 128","stacktrace":"main.main\n\t/go/src/github.com/tektoncd/pipeline/cmd/git-init/main.go:37\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:198"}

Step failed

```

**Comment by marikaj123** [comment] 2019-09-23 18:42
@tseelbach - this is needed by Epic: https://github.com/kabanero-io/roadmap/issues/67. Add the Epic release value here

**Comment by aadeshpa** [comment] 2019-09-30 15:18
We were able to reproduce it when we have our project in `github.ibm.com` and then it is mandatory to setup a github secret. If user miss to do that you get the error shown in description of this issue.
 
After investigation we found it comes from Tektoncd code.
Below is the direct link to the Tekton code from where the error is coming which we see after the failure of the pipeline.

https://github.com/tektoncd/pipeline/blob/master/pkg/git/git.go#L35

The problem is the error is not showing clear message that github secret is missing.

**Comment by tseelbach** [comment] 2019-09-30 16:39
Mark is there an open issue in tektoncd to make the message more clear when secret is missing?

**Comment by mnuttall** [comment] 2019-10-02 07:40
Hi @tseelbach there are 194 issues under https://github.com/tektoncd/pipeline/issues. I've looked through them and no, and cannot see that there's an open issue for this.

**Comment by anneqm** [comment] 2019-10-02 14:52
The following has been added to the Tekton Dashboard README file to help address the issue:
```Keep in mind that when running your Tekton Pipelines, if you see a `fatal: could not read Username for *GitHub repository*: No such device or address` message in your failing Task logs, this indicates there is no `tekton.dev/git` annotated GitHub secret in use by the ServiceAccount that launched this PipelineRun. It is advised to create one through the Tekton Dashboard. The annotation will be added and the specified ServiceAccount will be patched.```
Consider adding a similar statement to the kabanero-pipelines troubleshooting guide and open an an issue in the tektoncd/pipline to ask for a more helpful error message.

**Comment by aadeshpa** [comment] 2019-10-02 15:47
We would open the issue in https://github.com/tektoncd/pipeline/issues as suggested above by @mnuttall . Also we would add the above note in our troubleshooting guide.

**Comment by stephenkinder** [comment] 2019-10-02 15:54
@aadeshpa  I've spoken with @mnuttall:  

> 

https://github.com/tektoncd/pipeline would be the place to raise it. This type of error can occur for a set of related reasons:
- The user has created a secret for github but not patched that secret onto the service account used by the PipelineRun or TaskRun in question, or
- The user has not created a secret for github, but has tried to patch the relevant service account, or
- The user has not created a secret for github and has not patched the relevant service account

After we open the issue, we should link to this issue; but we should also update our troubleshooting guide in the short term to help customers resolve this issue for usage with Kabanero

**Comment by marikaj123** [comment] 2019-10-02 23:47
@aadeshpa - May you please provide us with the link to the issue that you have opened under https://github.com/tektoncd/pipeline for the Tekton team to have it completed during the next release.  As well, please provide us with the link to the issue that updates the troubleshooting guide that is required for this release.

**Comment by aadeshpa** [comment] 2019-10-03 11:50
@marikaj123 : Please find the issue created in the repository: https://github.com/tektoncd/pipeline/issues.

https://github.com/tektoncd/pipeline/issues/1375

**Comment by aadeshpa** [comment] 2019-10-03 12:45
Below is the pull request to update the note in our troubleshooting guide.
https://github.com/kabanero-io/kabanero-pipelines/pull/80

**Comment by aadeshpa** [comment] 2019-10-04 16:19
The troubleshooting pull request is merged. Closing this issue. 


To track the issue we opened :- tektoncd/pipeline#1375
we have created a tracker issue in our pipelines repo as per discussion with @tseelbach .
https://github.com/kabanero-io/kabanero-pipelines/issues/81

**Closed** 2019-10-04 19:14 UTC
Labels: SVT, status-Green
