### ISSUE TITLE
Pipeline validation does not work for multiple stacks

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-pipelines#172] opened 2020-01-27 18:36 UTC
Kabanero 0.5 has ability to define multiple stacks with different versions. But pipeline is not able to validate multiple stacks correctly.

￼￼￼Below is an example, although this stack is active, pipeline validation is failing.
```
spec:
  desiredState: active
  name: java-microprofile
  repositoryUrl: https://github.com/kabanero-io/collections/releases/download/0.5.0-rc.3/kabanero-index.yaml
  version: 0.2.21
  versions:
  - desiredState: active
    repositoryUrl: https://github.com/kabanero-io/collections/releases/download/0.5.0-rc.3/kabanero-index.yaml
    version: 0.2.21
  - desiredState: active
    repositoryUrl: https://github.com/kabanero-io/collections/releases/download/0.2.0/kabanero-index.yaml
    version: 0.2.18
```
![image](https://user-images.githubusercontent.com/29490950/73202769-bf680d80-4109-11ea-80e0-4095119db61d.png)

**Comment by smcclem** [comment] 2020-01-28 17:38
@mtamboli  Looking at 0.5.0 collection you pointed to as active:

https://github.com/kabanero-io/collections/releases/download/0.5.0-rc.3/kabanero-index.yaml

The stack images are now in the form:

   image: **docker.io/kabanerobeta/java-microprofile:0.2**

From your pipeline run, it appears your project had an appsody stack created from an older collection version, because the collection / appsody stack image is:

kabanero/java-microprofile:0.2.18

So it doesn't appear the issue was related having multiple stack version active in this case.

**Comment by mtamboli** [comment] 2020-01-28 18:37
@smcclem it will depends on which collections are activated. 

* When we have rc collections (https://github.com/kabanero-io/collections/releases/download/0.5.0-rc.3/kabanero-index.yaml), stack images are pushed to kabanerobeta so it make sense to define that in the appsody-config.yaml
https://hub.docker.com/r/kabanerobeta/java-microprofile

* Since there is another collections GM (https://github.com/kabanero-io/collections/releases/download/0.2.0/kabanero-index.yaml) which are active, its images will be in `kabanero`. 
https://hub.docker.com/r/kabanero/java-microprofile

kabanero.io is default so I nothing is specified, pipelines assume Kabanero.io. I also tried `kabanero.io/kabanero/java-microprofile:0.2.18` and it failed too.

We discussed this with @stephenkinder  and @kvijai82

**Comment by marikaj123** [comment] 2020-01-31 19:49
@stephenkinder - Need to decide if this issue is needed for Stacks design in 0.6.0?

**Comment by marikaj123** [comment] 2020-02-06 15:45
According to @smcclem -  Issue 172 wasn't a regression or defect.  The currect Kabanero release does not have an official support for multiple stack versions. The change she made to cause the break wasn't a change that was documented as being supported.

**Comment by marikaj123** [comment] 2020-02-06 15:51
Scott is working on delivering the multiple stack versions using https://github.com/kabanero-io/kabanero-pipelines/issues/196. 
Issue 196 has dependencies on both the Operator, and I think collections. which are mostly in place for issue 196 to use.  The plan is to try to ship as much as possible in 0.6.0 and the rest of the work will complete by the next release.

**Comment by marikaj123** [comment] 2020-02-06 15:59
According to Monica, it would help us to sync with @smcclem and @stephenkinder to answer the following questions:
        1. - Is this correct scenario for 0.6.0?
        2. - If yes, would some one make sure that this is fixed/added in 0.6 before SVT?
        3. - If this is not valid for 0.6/ICPA4.1 - we will not add the scenario to SVT list

**Comment by stephenkinder** [comment] 2020-02-06 16:02
The operator was enhanced in the previous milestone to understand stacks that have multiple versions active; it was a tactical step forward until we can improve the CLI, Dashboard and Governance task to consider multiple-versions; which we are delivering for 0.6.0 -- at this time multiple version stack governance will be supported.

The governance task will be enhanced to consider the container digests, so we can ensure that a build for container tags with only the Major Version or Major & Minor versions are building against active stacks.  The digests ensure that the customer does not have a process issue with managing their container tags in the target registry -- and ensure that only stacks that the enterprise wants too be built are being used.

**Comment by marikaj123** [comment] 2020-02-07 17:59
Vijai and team will be providing the fix into the GMC release.

**Comment by marikaj123** [comment] 2020-02-13 19:06
Fix going into rc2.

**Comment by kvijai82** [comment] 2020-02-13 21:36
Fix is in 0.6.0 rc2.  @mtamboli please verify when you get a chance.  Thanks!

**Comment by mtamboli** [comment] 2020-02-26 01:11
I think I am able to verify this defect as validate seems to be working as expected for below 3 cases:

There are 2 stacks active as seen in the below output. 
**(VERSIONS = 0.3.23  0.3.21)**
Case 1)  old version 0.3.21 in .appsody-config.yaml:` stack: kabanerobeta/java-spring-boot2:0.3.21` 

```
Git project config in .appsody-config.yaml... 
VERSION = 0.3.21
STACK_IMAGE_REGISTRY = 
PROJECT = kabanerobeta
STACK_NAME = java-spring-boot2
RECONCILED_STACK_IMAGE_REGISTRY_HOST = docker.io

In the cluster...
STACK_IMAGE = docker.io/kabanerobeta/java-spring-boot2
docker.io/kabanero/java-spring-boot2
STACK_IMAGE_REGISTRY = docker.io
PROJECT = kabanerobeta
STACK_NAME = java-spring-boot2 docker.io
VERSIONS = 0.3.23
0.3.21

Cluster stack version: 0.3.23, Cluster stack digest: "sha256:a366098a728213ee59c372de4dcbf4139df7630791af21b58df1e7785e81fffc"
Project stack version: 0.3.21, Project stack digest: "sha256:761b3e520e3ab7f20681fa4328d86649f2cef3895af6fcff2519a12a0ddea216"
The application stack, kabanerobeta/java-spring-boot2:0.3.21, in .appsody-config.yaml is active on this cluster and can be built.
```
Case 2: .appsody-config.yaml:` stack: kabanerobeta/java-spring-boot2:0.3.23`
```
{"level":"info","ts":1582675508.3405507,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
Git project config in .appsody-config.yaml... 
VERSION = 0.3.23
STACK_IMAGE_REGISTRY = 
PROJECT = kabanerobeta
STACK_NAME = java-spring-boot2
RECONCILED_STACK_IMAGE_REGISTRY_HOST = docker.io

In the cluster...
STACK_IMAGE = docker.io/kabanerobeta/java-spring-boot2
docker.io/kabanero/java-spring-boot2
STACK_IMAGE_REGISTRY = docker.io
PROJECT = kabanerobeta
STACK_NAME = java-spring-boot2 docker.io
VERSIONS = 0.3.23
0.3.21

The application stack, kabanerobeta/java-spring-boot2:0.3.23, in .appsody-config.yaml is active on this cluster and can be built.
Version 0.3 is validating correctly
```

Case 3: .appsody-config.yaml:` stack: kabanerobeta/java-spring-boot2:0.3`

```
VERSION = 0.3
STACK_IMAGE_REGISTRY = 
PROJECT = kabanerobeta
STACK_NAME = java-spring-boot2
RECONCILED_STACK_IMAGE_REGISTRY_HOST = docker.io

In the cluster...
STACK_IMAGE = docker.io/kabanerobeta/java-spring-boot2
docker.io/kabanero/java-spring-boot2
STACK_IMAGE_REGISTRY = docker.io
PROJECT = kabanerobeta
STACK_NAME = java-spring-boot2 docker.io
VERSIONS = 0.3.23
0.3.21

The application stack, kabanerobeta/java-spring-boot2:0.3, in .appsody-config.yaml is active on this cluster and can be built.
```

@smcclem @stephenkinder @kvijai82 Is that what you expected too?

**Comment by kvijai82** [comment] 2020-02-26 13:11
@mtamboli That sounds right to me.

**Closed** 2020-02-26 23:09 UTC
Labels: SVT, bug
