### ISSUE TITLE
PipelineRun->utilities-task is shown code for the logs

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-pipelines#304] opened 2020-04-14 11:40 UTC
When using Kabanero 0.8.0-rc.1, there is a new task utilities-task and sub tasks is showing code under logs.

![image](https://user-images.githubusercontent.com/29490950/79220981-05885f80-7e23-11ea-959a-becad3619137.png)

**Comment by smcclem** [comment] 2020-04-14 15:15
This is by design, all the utilities tasks display the full script they are copying to the workspace.   

We have a plan to preface all the output in our logs with :

[INFO]
[WARN]
[ERROR]. 

to make it obvious to the reader what the intention and severity of the output is.

**Comment by mtamboli** [comment] 2020-04-14 15:38
@scottkurz Can you please explain the purpose of these tasks? So they are not running actual task?
I saw failure in one them.
![image](https://user-images.githubusercontent.com/29490950/79243757-10072100-7e44-11ea-98f3-9142395b1a58.png)

Also, I wanted to see output of enforce-stack-policy was doing especially when this task failed later in the build. So we are not really running this task as part of the utility-task?
![image](https://user-images.githubusercontent.com/29490950/79243935-4644a080-7e44-11ea-9aa9-9a39de52c04a.png)

**Comment by smcclem** [comment] 2020-04-14 19:03
The utilities task is just writing out scripts to be used later in the workspace by other tasks. The enforce stack policy happens in the build-push task.  See "enforce-stack-policy-pre-build" and "enforce-stack-policy-post-build".  This is where the script that was laid down in the utilities task is run.  

Your failure in the utilities task said it failed because of a previous step failure.   Doesn't look like a failure in the utilities task itself.

**Comment by mtamboli** [comment] 2020-04-14 19:52
@smcclem Can we create description for the utility-task explaining its purpose? I was expecting the output of the commands in the log.

Utility-task is the first task so nothing really before it. The above failure was because GHE secret was not created correctly. Would `Utility-task` fail if it could not get top the project in GHE?

**Comment by marikaj123** [comment] 2020-04-16 17:25
Vijai and Monica decided to have the appropriate fix in Kabanero 0.9.0.

**Comment by kvijai82** [comment] 2020-04-17 15:54
Plan is to remove the whole utilities task and put the scripts in kabanero-utils image in https://github.com/kabanero-io/kabanero-pipelines/issues/313

**Comment by kvijai82** [comment] 2020-05-01 10:54
@mtamboli we completed the work to remove the utilities task in 0.9.0.  So you should not see this anymore.  Please let me know if we should just close this now or you want to wait to verify this in the RC.

**Comment by mtamboli** [comment] 2020-05-01 11:29
@kvijai82 Feel free to close this if already fixed.

**Comment by aadeshpa** [comment] 2020-05-01 18:58
Marking this as closed, since we moved the utilities task scripts out to kabanero-utils image as part of this issue.

**Closed by aadeshpa** 2020-05-01 18:58 UTC
Labels: SVT, bug
