### ISSUE TITLE
Rework of validation task in pipeline using digests

### ISSUE THREAD

**Issue by kvijai82** [kabanero-io/kabanero-pipelines#274] opened 2020-03-23 16:51 UTC
We have a new spec to guide how we handle validation in pipelines that's documented here:   https://github.com/kabanero-io/kabanero-foundation/blob/master/design/digest.md

**Comment by tseelbach** [comment] 2020-03-24 19:38
closing as duplicate of https://github.com/kabanero-io/kabanero-pipelines/issues/267

**Closed by tseelbach** 2020-03-24 19:38 UTC
Labels: documentation-id
